### PR TITLE
Levelspace extension models, closes #277

### LINKED ISSUE #277: New Model(s): LevelSpace Code Examples
To be located in the `Code Examples/Extensions Examples/ls` folder.

At an earlier meeting, we discussed having 2 (possibly 3) examples:
1. An example showing how to open models in LevelSpace
2. An example with turtles, where each turtle has a child model associated with it (then in the `go` each turtle asks its model to `go`

### PR DESCRIPTION
**Pull request by arthurhjorth**
Added all three examples. I know that the hardcoded paths inside the Visualizer and the Interactions need to be changed so that they point to the **library versions** of respectively WSP, and WSP and CC. However, I'm not sure how that works cross-platforms, and I I am only on Windows now. Happy to change if someone will tell me what they should be. 

I think at one point we talked about making the WSP-CC Interactions model a non-Code Example, but the actual logic of the model is literally three lines, so I think it's better like that. It also emphasizes interactions between models in a way that the other two code examples do not. What do you think?

### CODE REVIEW

**Comment by bainco** [comment]
Things left to do:

- [ ] Proof info tabs

- [ ] make sure someone who doesn't know how to use LS can utilize these examples

- [ ] Add custom screenshots for all 3

1. For Model Loader, I was thinking just a combined screenshot of a couple of different GUI models stacked on top of each other vis-a-vis [this](https://res.cloudinary.com/igdb/image/upload/t_screenshot_big/x2x9esxoplcexp0e6uui.jpg)
2. For Model Interactions, a side-by-side of WSP and CC would be nice
3. For Model visualizer and Plotter, maybe just a full interface shot (including widgets)

- [ ] Check on how to reference built in Sample models (currently uses POSIX file paths)

Note: Travis tests will fail because LS is not yet bundled into NetLogo/NetLogo

**Comment by bainco** [comment]
@nicolaspayette could you take a look at these? Particularly:

>  Talk about forbidden primitive no-display in Model Interactions.
I think this is a reasonable use of `no-display` / `display`. Do you agree?

> Investigate why the Notarizer is failing on all three.
The notarizer test is currently failing (on the `diff` part of the test). I have no idea why.

>  Make sure someone who doesn't know how to use LS can utilize these examples
I think they're fine...but I guess this kind of depends on extension documentation as well

**Comment by nicolaspayette** [comment]
> I think this is a reasonable use of `no-display` / `display`. Do you agree?

Yeah, it seems like LevelSpace introduces a genuine use case for `no-display`. Unless someone finds a way around it, I think it may warrant an exception in https://github.com/NetLogo/models/blob/master/src/test/scala/org/nlogo/models/CodeTests.scala#L84.

> Investigate why the Notarizer is failing on all three.

It fails because the copyright notice doesn't appear in the code tab. If you `runMain org.nlogo.models.Notarizer` from `sbt`, the Notarize should do its job and add the notice.

The test that is failing is comparing the model file to the output of re-running the Notarizer and failing because of the discrepancy.

> I think they're fine...but I guess this kind of depends on extension documentation as well

They look good at first glance. I'll try to give all three of them a better very soon.

**Comment by nicolaspayette** [comment]
I reviewed all three models from a "user perspective" and they look good to me. My only minor complain is that, if you don't click **setup models** before clicking **go**, you're liable to get exceptions exceptions from the child models.

I'm wondering if it should be `setup-models` that calls `reset-ticks` instead of `setup`, but I haven't thought about it deeply. @arthurhjorth, @bainco does that make sense to you?

(In any case, that's not a deal breaker.)

**Comment by bainco** [comment]
That seems reasonable. The main thing people need to learn, is that in LS, you have to have a setup method for your model and THEN you also have to call setup in each individual child model. I think your suggestion makes sense.

**Comment by nicolaspayette** [comment]
I am merging this with the tests still pointing to the `NetLogo/levelspace` branch. We'll point the `master` tests back to `NetLogo/hexy` once https://github.com/NetLogo/NetLogo/pull/1140 is merged.

**Pull request merged**
