### PR TITLE
Tree Model: Altered Slider

### PR DESCRIPTION
**Pull request by barbacbd**
** Update the slider to use the max/min size if the value is outside of the boundaries. This will
also cause the slider values to be reset so the user can see them.

#399

### CODE REVIEW

**Review by LaCuneta — CHANGES_REQUESTED** [review]
Thank you for your contribution!

So this fix works, but I think the simpler method would be to use the fix proposed in the original issue and set the slider min/max to 100 to match the defined view sizes.  We try to keep the models library samples simple and understandable, and people might get confused on why the sliders allowed values outside the acceptable world range.

And one side note - it seems the default value of the slider got changed from -50 to 0.  That can happen unintentionally when making model changes since it's common to make widget changes while testing.

If you want to update the PR to resolve those two items I'd be happy to merge.

**Comment by barbacbd** [comment]
Absolutely I will squash the commit and change the default back to -50. That was probably done in testing like you said.

**Review by LaCuneta — APPROVED** [review]
Nice, thank you again!

**Comment by LaCuneta** [comment]
Oof, I'm terribly sorry, but it turns out some "in flight" work just got merged that separately resolved this:  https://github.com/NetLogo/models/commit/8e006fbdeb5b3a1032b515f000d3415d984ad986

I would never have asked for the changes if I'd noticed that.  My sincere apologies.  Thank you again for your contribution.

Since there isn't anything to merge now, I'll go ahead and close this.

**Pull request closed without merging**
