### PR TITLE
Simple Economy: put back max/min-n-of in plotting code

### LINKED ISSUE #112: Simple Economy: put back max/min-n-of in plotting code
67e4ec8ca64a1f202cdd3d69668be4212600b7bb replaced the use of `max-n-of` and `min-n-of` by alternative code using `sort` to get around the fact that `max-n-of` and `min-n-of` are not yet available in NetLogo Web. Once they are, however, we should revert that change because the original code was simpler and clearer.

Maybe that will also be the occasion to replace hard coded numbers 50 and 250 with actual percentage calculations, making the plot more robust in case someone changes the population (there is no slider for that but a user could easily modify the code).

### PR DESCRIPTION
**Pull request by nicolaspayette**
This should close #112.

One thing before I merge, though. The info tab says:

> ## NETLOGO FEATURES
>
> This model makes extensive use of the "widget" based graph methods.

I have no idea what that means. (Unless it refers to having the plotting code inside the plot as opposed to the code tab?) Can someone shed some light on this?

### CODE REVIEW

**Comment by SethTisue** [comment]
> Unless it refers to having the plotting code inside the plot as opposed to the code tab

That's what I would guess.

It seems like a reach to consider this notable, since NetLogo 5.0 has now been around for so long, but maybe it seemed notable at the time.

**Comment by nicolaspayette** [comment]
@qiemem, since [you claim having done it before](https://github.com/NetLogo/NetLogo/issues/744#issuecomment-86953921), would you mind taking a look at my workaround for https://github.com/NetLogo/NetLogo/issues/744: 77ea79a. Any way I could have done this better?

**Comment by nicolaspayette** [comment]
Proposed new text for the NETLOGO FEATURES section:

> NetLogo plots have an auto scaling feature that allows a plot's x range and y range to grow automatically, but not to shrink. We do, however, want the y range of the WEALTH DISTRIBUTION histogram to shrink since we start with all 500 turtles having the same wealth (producing a single high bar in the histogram), but the distribution of wealth eventually flattens to a point where no particular bin has more than 40 turtles in it.

> To manually adjust the histogram's y range, we use the [`set-plot-y-range`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#set-plot-y-range) command. Look at the histogram's pen update commands to see how it is done.

@UriCCL, the latest version of the model is downloadable at https://raw.githubusercontent.com/NetLogo/models/simple-econ-max-n-of/IABM%20Textbook/chapter%202/Simple%20Economy.nlogo if you want to see it.

**Comment by qiemem** [comment]
Indeed I believe there is! If you turn auto-scale on, you can just run `set-plot-y-range 0 1` on updates. The auto-scale will then push the graph up to where it needs to be.

**Comment by nicolaspayette** [comment]
> If you turn auto-scale on, you can just run `set-plot-y-range 0 1` on updates. The auto-scale will then push the graph up to where it needs to be.

Oh wow! That is much simpler indeed! I will use that instead and adjust my FEATURES text accordingly.

**Comment by nicolaspayette** [comment]
Updated second paragraph of NETLOGO FEATURES:

> To get NetLogo to correctly adjust the histogram's y range, we use [`set-plot-y-range 0 40`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#set-plot-y-range) in the histogram's pen update commands and let auto scaling set the maximum higher if needed.

Clear enough?

(BTW, I'm making sure the top of the range doesn't shrink below 40 to stay consistent with screenshots in the book.)

**Comment by qiemem** [comment]
LGTM

**Pull request merged**
