### PR TITLE
Fix Traffic Basic Adaptive

### PR DESCRIPTION
**Pull request by qiemem**
Not sure where we're ending up on the speed limit thing, but here's all the updates for Traffic Basic Adaptive. They're pretty extensive. They include:

- Fix algorithm by not reseting after first tick of sample period
- Improve algorithm to make it robust against spikes due to noise
- Clean up code
- Improve user interface
- Update info tab

### CODE REVIEW

**Comment by qiemem** [comment]
Ah, crap, didn't notice you updated the traffic models again. Let me know how you'd like me to resolve it.

**Comment by nicolaspayette** [comment]
No worries. I'll take care of the merge.

**Comment by qiemem** [comment]
You're the best! Thanks! :star:

**Comment by nicolaspayette** [comment]
@qiemem, can you take a quick look at the version now in `master` to make sure I didn't mess up anything in the merge?

**Comment by qiemem** [comment]
With `speed-limit` gone, you could move buttons + acceleration monitors + view up a bit to make it somewhat more compact. Up to you.

**Comment by nicolaspayette** [comment]
Good point, @qiemem. Done in c9ff710.

**Pull request merged**
