### PR TITLE
Make blue the last turtle instead of third last

### PR DESCRIPTION
**Pull request by Suppaman**
Using indices makes blue the third last ant (code bug?) instead of the last one as explained in the info tab.
PROPOSAL: use (max [who] of turtles) instead of (num-ants - 1)

### CODE REVIEW

**Comment by SethTisue** [comment]
good catch! another possible fix would be `ask last sort turtles`

**Comment by nicolaspayette** [comment]
Good catch indeed! I normally would prefer @SethTisue's suggestion of `last sort turtles` instead of `turtle max [who] of turtles` because the intent seems clearer and I think it's generally better to avoid using `who` numbers. But since this particular model already uses `who` numbers in several places, we might as well go with yours.

Thanks!

**Comment by Suppaman** [comment]
I think yours is a more elegant solution!
The error seems to be introduced when two turtles are created (and asked to die) in order to stamp the nest and food circles.

BTW, I also noticed that the leader is asked to wiggle only to have its heading reset to 90 some lines below in the setup procedure (asking ALL turtles regardless of breed). Could be protected with ```if (breed != leaders) [ set heading 90 ]``` after ```setxy nest-x nest-y```, asking followers separately after setting the coordinates for all (alive) turtles,  or have ```wiggle 50``` eliminated altogether.

**Comment by nicolaspayette** [comment]
> The error seems to be introduced when two turtles are created (and asked to die) in order to stamp the nest and food circles.

Makes sense! That's also a good example of why trying to think in `who` numbers often leads to errors.

> BTW, I also noticed that the leader is asked to wiggle only to have its heading reset to 90 some lines below in the setup procedure (asking ALL turtles regardless of breed). Could be protected with `if (breed != leaders) [ set heading 90 ]` after `setxy nest-x nest-y`, asking followers separately after setting the coordinates for all (alive) turtles, or have `wiggle 50` eliminated altogether.

You're right! Will fix.

**Comment by nicolaspayette** [comment]
> the leader is asked to wiggle only to have its heading reset to 90 some lines below in the setup procedure

Fixed in https://github.com/NetLogo/models/commit/eadadd1b297956ec2c59c4f4d056320ad1e2cc15.

Thanks again!

**Pull request merged**
