### PR TITLE
Use sbt and Travis to run tests on models

### PR DESCRIPTION
**Pull request by nicolaspayette**
Part of our quality control process for the models library currently involves a bunch of Scala scripts that need to be run manually around release time (https://github.com/NetLogo/models/tree/master/bin). It would be much better to catch the problems detected by these scripts as soon as changes are pushed to the repo.

Hence this pull request.

It uses a minimal `sbt` build and `scalatest` to allow writing proper tests to be run by Travis. I plan to use it first for https://github.com/NetLogo/models/issues/53 and then convert the scripts in `bin/` as I go along. `notarize.scala` could be turned into an sbt task should it still be needed after we tackle https://github.com/NetLogo/NetLogo/issues/746 (we could also have the tests do a dry run of `notarize`).

- @frankduncan, this affects `release.sh` as there will be a few more files to clean up when bundling models (`.travis.yml`, `sbt`, `build.sbt`, `project/` and `src/`, if I'm not mistaken).

- @TheBizzle, @mrerrormessage, @qiemem: would it affect Tortoise if I merged this?

Any other comments/warnings/suggestions?

### CODE REVIEW

**Comment by TheBizzle** [comment]
> would it affect Tortoise if I merged this?

Not that I'm aware of.  Is there anything in particular here that seemed to you like it could possibly make problems for Tortoise?

**Comment by nicolaspayette** [comment]
> Is there anything in particular here that seemed to you like it could possibly make problems for Tortoise?

The only thing I had in mind was extra files/folders accidentally appearing in the drop down list of available models. But if you only list `.nlogo` files in there, it shouldn't be a problem.

**Comment by TheBizzle** [comment]
Yeah, no problems on that front.

**Comment by SethTisue** [comment]
great idea

**Pull request merged**
