### PR TITLE
Chapter 5 fixes

### PR DESCRIPTION
**Pull request by qiemem**
Discussed with Uri for class.

### CODE REVIEW

**Comment by nicolaspayette** [comment]
Looks great at first glance. Will review more thoroughly and merge next week.

**Comment by nicolaspayette** [comment]
@qiemem, a couple of questions about *Preferential Attachment Simple* before I merge:

- Should the info tab say something about the new degree distribution plot?
- In the original *Preferential Attachment* model, the degree distribution histogram is a a bar plot. Here, it is a line plot. Any reason?

I like your new layout code, by the way. I find it much nicer than the one in the original ("non simple") model.

**Comment by nicolaspayette** [comment]
I added some text to the info tab and changed the histogram for a bar plot (see a3a7c96 commit message for justification). Merging.

**Comment by qiemem** [comment]
Thanks! Sorry for not getting back about your comments. Your changes look good.

**Comment by nicolaspayette** [comment]
No problem! :-)

**Pull request merged**
