### PR TITLE
Fix documentation issues in various models

### PR DESCRIPTION
**Pull request by nicolaspayette**
Many thanks to Ken Khan (@ToonTalk) for reporting these. I can't stress enough how much this is appreciated.

### CODE REVIEW

**Comment by SethTisue** [comment]
> I can't stress enough how much this is appreciated.

yes, thank you Ken

**Comment by ToonTalk** [comment]
Glad to help. I assigned 30 university students to pick a model and answer
some questions. To evaluate their answers I needed to know the 20 models
chosen pretty well.

By the way, it wasn't clear if I should bother to post suggestions. For
example, the Autumn model has many display modes that neither I nor the
student could tell the difference visually. I did confirm that it is
working but very hard to see. I suggest either remove this feature or
implement it in a way that is perceptually easier to see (e.g. use size).

Best,

-ken

**Comment by OASCCL** [comment]
Thanks so much Ken.
Your feedback is very much appreciated.

—Uri

Uri Wilensky

**Comment by nicolaspayette** [comment]
> I assigned 30 university students to pick a model and answer some questions.

Please don't hesitate to report new issues/suggestions if anyone finds anything in the process!

Regarding **Autumn**, I have opened #195.

**Comment by nicolaspayette** [comment]
Fixed in dbdd2f3c7a2908b4ff7981888b35202999955e5d.

**Pull request merged**
