### PR TITLE
Store copyright and citation information in the models themselves

### LINKED ISSUE #42: IABM citations are not consistent
reported by @SethTisue:

"There is a lot of general inconsistency about whether citation information is indented with a bullet or not. see e.g. the info tab of Fire Simple. The info tab contains a total of eight citations. Four are bulleted, four are not.

I suggest using the bullets because it calls the citation out as something most readers won't need to read."

### PR DESCRIPTION
**Pull request by nicolaspayette**
# How it was before

Model files _in the repo_ did not contain copyright/how to cite information. (Those in the release, of course, did.) This information was, instead, contained in a file called `legal.txt`. At release time, we had a script called `notarize.scala` that used the information contained in `legal.txt` to generate HOW TO CITE and COPYRIGHT AND LICENSE.

# Why this was not ideal

- Models in the repo were different from models in the release, with the consequence that, whenever released models were used as a basis for modification, copyright/citation information had to be manually stripped out (on pain of having `notarize.scala` crash at release time).

- Since `notarize.scala` was a release-time thing, problems with copyright/citation info were often discovered at the very last minute.

- While the citation/copyright info for models in the repo *was* available in `legal.txt`, it was not as convenient/prominent as having it in the models themselves.

# Requirements for a solution

The previous way of doing things was not perfect, but it was solving a very important problem: manually maintaining citation/copyright information in hundreds of models is tedious and error prone: problems are hard to detect and tend creep in; consistency is all but impossible to maintain and bulk modifications are difficult.

Thus, any new solution needed to:

- automatically detect errors as soon as possible;

- allow bulk generation/modification of citation/copyright information;

- keep model files in the repo identical to those in the release.

# How it will work now

- The entire HOW TO CITE and COPYRIGHT AND LICENSE sections are now stored in the model files in the repo (just like in released models).

- What I call the "legal snippet" (the small piece of text that used to be in `legal.txt`, e.g.: `2008 NIELS Cite: Sengupta, P.`) is now stored as an HTML comment at the end of the info tab. (E.g., `<!-- 2008 NIELS Cite: Sengupta, P. -->`). Since it's a comment, it appears in "edit" mode, but not when the info tab is rendered. It's both convenient and non-obtrusive!

- Any time a change to a model is committed to the repo, automated tests check that the content of HOW TO CITE and COPYRIGHT AND LICENSE sections matches what it should be, given the content of the legal snippet.

- A "Notarizer" program (https://github.com/NetLogo/models/blob/wip-legal/src/test/scala/org/nlogo/models/Notarizer.scala) is still available to replace the content of relevant sections with automatically generated output. That's useful for:

  - generating citation/copyright info the first time around;
  - undoing accidental modifications;
  - doing bulk modifications if something changes in the way we generate that information.

Note that IABM textbook models are now handled by the Notarizer program and associated tests. (They were handled manually for 5.2.0.) That includes the ACKNOWLEDGMENT section at the top of the info tab.

Some other notes:

- Working on this pull request required fixing lots of little stuff in the models; too many small things to list here. Look at the commits.

- This should close #42.

- #59 will need to take this work into account.

### CODE REVIEW

**Comment by SethTisue** [comment]
:clap:

**Comment by TheBizzle** [comment]
:+1:

**Comment by SethTisue** [comment]
@reuven might enjoy this

**Comment by arthurhjorth** [comment]
:earth_asia: :earth_africa: :earth_americas: :clap:

**Pull request merged**
